# [NumPy](https://numpy.org/)

**Goal:** create, reshape, index, and summarize arrays used in statistical computing.

## Overview

NumPy provides fast, homogeneous arrays and vectorized numerical operations. This tutorial moves from array creation to shape, data types, file input, and indexing.

Keep three questions in mind: **What is the shape? What is the dtype? Which axis is being reduced?** For reproducible simulations, use a seeded generator such as `np.random.default_rng(1234)`.

See the [NumPy User Guide](https://numpy.org/doc/stable/user/index.html) for further detail.

For example, suppose we want to create an array of 1 million random draws from a uniform distribution and compute the mean.

If we did this in pure Python it would be orders of magnitude slower than C or Fortran.

This is because

- Loops in Python over Python data types like lists carry significant overhead.
- C and Fortran code contains a lot of type information that can be used for optimization.
- Various optimizations can be carried out during compilation when the compiler sees the instructions as a whole.

However, for a task like the one described above, there’s no need to switch back to C or Fortran.

Instead, we can use NumPy, where the instructions look like this:

In [2]:
import numpy as np

In [10]:
x = np.random.uniform(0, 1, size=10000)

In [11]:
np.mean(x)

0.5039262986548112

In [12]:
x.mean()

0.5039262986548112

In [ ]:
x = np.random.uniform(0, 1, size=100)
# print(x)
# x
# np.mean(x)
# x.mean()

The operations of creating the array and computing its mean are both passed out to carefully optimized machine code compiled from C. More generally, NumPy sends operations in batches to optimized C and Fortran code. This is similar in spirit to Matlab, which provides an interface to fast Fortran routines.

NumPy is great for operations that are naturally vectorized. Vectorized operations are precompiled routines that can be sent in batches, like

- matrix multiplication and other linear algebra routines
- generating a vector of random numbers
- applying a fixed transformation (e.g., sine or cosine) to an entire array

## 1. NumPy Arrays

- NumPy's core object is the [`ndarray`](https://numpy.org/doc/stable/reference/arrays.ndarray.html).
- An array has a fixed shape and normally stores values of one data type.
- NumPy arrays power a large proportion of the scientific Python ecosystem.

In [14]:
a = np.ones(5)

In [17]:
type(a[0])

numpy.float64

In [ ]:
# a = np.zeros(20)
a = np.ones(5)*3
# print(a)

In [ ]:
a

In [ ]:
type(a)

In [ ]:
type(a[0])

NumPy arrays are somewhat like native Python lists, except that
- Data must be homogeneous (all elements of the same type).
- These types must be one of the data types (dtypes) provided by NumPy.

The most important of these dtypes are:
- float64: 64 bit floating-point number
- int64: 64 bit integer
- bool: 8 bit True or False

There are also dtypes to represent complex numbers, unsigned integers, etc.

NumPy infers a dtype from the input; constructors such as `np.zeros` default to floating point. Check `.dtype` when precision or memory use matters.

In [20]:
a = np.zeros(3)
type(a[0])

numpy.float64

If we want to use integers we can specify as follows:

In [21]:
a = np.zeros(3, dtype=int)
type(a[0])

numpy.int64

### Shape and dimension
Consider the following assignment

In [24]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
z.shape = (2, 5)

In [41]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Here `z` is one-dimensional—neither a row matrix nor a column matrix.

The dimension is recorded in the <font size = 4>shape</font> attribute, which is a tuple

In [ ]:
z.shape

Here the shape tuple has only one element, which is the length of the array (tuples with one element end with a comma).

To make it two-dimensional, we can change `shape`. The new shape must contain exactly the same number of elements.

In [ ]:
z.shape = (10,1)

In [ ]:
z.shape

In [ ]:
z.shape = (5, 2) # this is an assignment
z

In [ ]:
z = np.zeros(4)
z.shape = (2, 2) # now we are making this a 2*2 matrix
z

In the last case, to make the 2 by 2 array, we could also pass a tuple to the <font size = 4>zeros()</font> function, as in <font size = 4>z = np.zeros((2, 2))</font>.

In [ ]:
z = np.zeros((2,2))
z 

## 2. Creating Arrays

As we’ve seen, the <font size = 4>np.zeros</font> function creates an array of zeros and <font size = 4>np.ones</font> creates an array of ones.

Related is `np.empty`, which allocates memory without initializing its values. Fill it before reading from it.

In [ ]:
z = np.empty(3)
z

The numbers you see here are garbage values.

(Python allocates 3 contiguous 64 bit pieces of memory, and the existing contents of those memory slots are interpreted as <font size = 4>float64</font> values)

To set up a grid of evenly spaced numbers use <font size = 4>np.linspace</font>

In [47]:
z = np.linspace(1, 10, 10)
z

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
z.shape = (5, 2)
z

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [ ]:
z = np.linspace(2, 20, 10)  # From 2 to 20, with 10 elements
z

To create an identity matrix use either <font size = 4>np.identity</font> or <font size = 4>np.eye</font>

In [ ]:
z = np.identity(3)
z

In addition, NumPy arrays can be created from Python lists, tuples, etc. using <font size = 4>np.array</font>

In [51]:
z = np.array([1, 2, 3, 4, 5, 6])
z.shape = (2,3)
z

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
z = np.array([[1, 2, 3], [4, 5, 6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
z.shape = (6, 1)

In [ ]:
z

In [ ]:
z = np.array([10, 20]) # ndarray from Python list
z

In [ ]:
type(z)

In [ ]:
z = np.array((10, 20), dtype=float) # Here 'float' is equivalent to 'np.float64'
z

In [ ]:
z = np.array([[1,2], [3,4], [5,6]]) # 2D array from a list of lists
z

In [ ]:
z.shape

For a regular numeric text file, use `np.loadtxt`; for missing values or mixed formatting, use `np.genfromtxt`. Inspect the resulting shape and dtype immediately.

In [55]:
z = np.loadtxt("gfr.txt", unpack=True)

In [58]:
type(z)

numpy.ndarray

In [ ]:
gfr = np.loadtxt("gfr.txt", unpack=True)
gfr.shape

In [ ]:
type(gfr)

## 3. Array Indexing
For a one-dimensional array, indexing follows Python sequence rules. Basic slices usually share memory with the original array, so modifying a slice can modify its source.

In [59]:
z = np.linspace(1, 10, 10)
z

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [63]:
z[1:4] # [2,5)

array([2., 3., 4.])

In [ ]:
z[3]

In [ ]:
z[1:4]  # Three elements, starting at index 1

In [64]:
z[-1] # the last element

10.0

In [66]:
z[-3]  # Third element from the end

8.0

For two-dimensional arrays, index rows first and columns second: `z[row, column]`.

In [ ]:
z = np.array([[1, 2], [3, 4], [5, 6]])
z

In [ ]:
z[1,:]

In [ ]:
z[0, 1]

Note that indices are still zero-based, to maintain compatibility with Python sequences.

Columns and rows can be extracted as follows

In [ ]:
z[1, :]

In [ ]:
b = z[:, 1]

In [ ]:
b.shape

Integer arrays perform fancy indexing. Unlike a basic slice, fancy indexing returns a copy.

In [ ]:
z = np.linspace(2, 4, 5)
z

In [ ]:
indices = np.array((0, 2, 3))
z[indices]

A Boolean mask selects entries where the mask is `True`. Its shape must match the axis being filtered, and the result is a copy.

In [ ]:
z 

In [ ]:
d = np.array([0, 0, 1, 0, 0], dtype=bool)
d

In [ ]:
z[d]

### Quick check
Create a 3 by 4 array, extract its second column, and compute each row mean with `axis=1`.

> **Watch for:** broadcasting can make incompatible-looking shapes run without an error; inspect shapes when a result is surprising.

**Takeaway:** array shape and indexing determine whether vectorized calculations do what you intend.